# Travis config file to build psycopg packages

sudo: required
dist: trusty

services:
    - docker
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        - WANT_LIBPQ="110001"

matrix:
    include:
        - os:
            osx
          osx_image:
            xcode9.2
          env:
            SCRIPT=./scripts/open_tunnel.sh

before_script:
    # Set up files required for upload
    - openssl aes-256-cbc
      -K $encrypted_bd656d6a5753_key -iv $encrypted_bd656d6a5753_iv
      -in id_rsa-travis-upload.enc -out /tmp/id_rsa-travis-upload -d
    - chmod 600 known_hosts /tmp/id_rsa-travis-upload
    - sudo ./scripts/configure_postgres.sh

script: $SCRIPT

# after_success: ./scripts/upload_packages.sh

notifications:
  email: false
